version: '3.9'

services:
  db:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: notifications-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
